# Numpy

- 수치해석용 Python 라이브러리
- CPython에서만 사용가능
- ndarray 다차원 행렬 자료 구조 제공
- 내부 반복문 사용으로 빠른 행렬 연산 가능
- 행렬 인덱싱(array indexing) 기능 제공

# List

- 여러형태 데이터 저장
- 값 추가 제거 가능
- 동적할당

# Numpy

- 한가지 데이터 저장
- 계산에 효율적(C기반 for문 내장)
- 정적할당 : 고정된 사이즈
- 사이즈 변경시 Array 삭제 후 새로운 Array 생성

In [2]:
# List 제곱하기

x = [10, 20, 30]
type(x)

list

In [3]:
# y=x*x # 리스트는 곱하기가 안된다

x[0]*x[0] # 성분별로 곱해줘야함
x[1]*x[1]
x[2]*x[2]

y=[i**2 for i in x]
print(x)
print(y)

[10, 20, 30]
[100, 400, 900]


In [4]:
# Numpy에서 제곱하기

import numpy as np
x = np.array([10,20,30])
y=x*2
print(y)

y = x**2
print(y)

[20 40 60]
[100 400 900]


In [6]:
# arange()

a = np.arange(10)
print(a)
a

a = np.array([10,20,30], 'float64') # 자료형을 따로 안넣어주면 int32로 들어감
a[0] += 1.1
a

[0 1 2 3 4 5 6 7 8 9]


array([11.1, 20. , 30. ])

In [7]:
# shape : 행렬의 차원

a.shape

(3,)

In [8]:
# ndim : dimension 차원

a.ndim

1

In [9]:
# dtype : data type

a.dtype

dtype('float64')

In [10]:
# itemsize

a.itemsize

8

In [11]:
# size : array 개수

a.size

3

In [12]:
# type()

type(a)

numpy.ndarray

In [13]:
# int32/int64

a=np.array([10,20,30])
b=np.array([10.,20.,30.])
print(a.dtype)
print(b.dtype)

a = np.array([10, 20, 30])
print(a.dtype)

a[2]= 30.1
print(a.dtype) # 중간에 값이 바껴도 처음 만들때 정해진 데이터 타입이 유지
print(a)

int32
float64
int32
int32
[10 20 30]


In [14]:
# astype : 데이터형 바꾸기

a = np.array([10,20,30])
print(a.dtype)

a=a.astype('float64') # 데이터 타입을 바꿈

a[2]= 30.1
print(a.dtype)
print(a)

x = np.array([7,9,11])
y = x/2
print(x.dtype)
print(y.dtype)

c=np.array([10.1, 20.1, 30.1], 'int32')
print(c.dtype)
print(c)

int32
float64
[10.  20.  30.1]
int32
float64
int32
[10 20 30]


# **2진수를 10진수로 변환 사이트**

[https://www.rapidtables.com](https://www.rapidtables.com/)

- int32 -> 2진수 31자리까지 표현(첫자리는 부호비트)
- 가장 큰수를 10진수로 변환하면 2147483647

In [16]:
x=np.array([0])
x[0]=2147483647
x

array([2147483647])

In [17]:
x=np.array([0],'int64') # 큰수는 애초에 64비트로 선언
x[0]=2147483647
x[0]+=1
print(x)

[2147483648]


In [20]:
# 다차원 array

x = np.array([10,'a',30])
x

array(['10', 'a', '30'], dtype='<U11')

In [21]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]]) # 대괄호가 2개다? 2차원
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9
2


In [22]:
a=np.array([[[10],[20]],[[30],[40]]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[[10]
  [20]]

 [[30]
  [40]]]
(2, 2, 1)
4
3


In [23]:
# insert()

a = np.array([10,20,30])
a = np.insert(a,0,5)
print(a)

[ 5 10 20 30]


In [24]:
# delete()

a = np.delete(a,0)
print(a)

[10 20 30]


In [25]:
# zeros(), ones(), linspace()

a=np.arange(3)
print(a)
print( )
a=np.zeros([2,3])
print(a)
print( )
a=np.ones([2,3])
print(a)
print( )
a=np.linspace(0,1,5)
print(a)
print( )

[0 1 2]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0.   0.25 0.5  0.75 1.  ]



In [26]:
# 연산

a = np.array([10,20,30])
b = np.array([1,2,3])
c = a+b
print(c)
c = a-b
print(c)

[11 22 33]
[ 9 18 27]


In [27]:
idx = b<20 # 행렬 데이터 들고와서 필터링할때 쓸수 있음
print(idx)

idx = a<20
print(idx)
print(type(idx))

[ True  True  True]
[ True False False]
<class 'numpy.ndarray'>


In [28]:
a = np.array([10,20,30])
a += 1 # c에서는 안된다..? 리스트에 더하기
print(a)
print(type(a))

[11 21 31]
<class 'numpy.ndarray'>


In [29]:
a = np.array([10,20,30])
b = np.array([1.,2.,3.])
a = a.astype('float64') # 이거 없으면 에러난다(int+float 이라서)
a+=b


In [30]:
# 연산함수

a = np.array([10,20,30])
b = np.array([1,2,3])
print(np.add(a,b))
print(np.subtract(a,b))

[11 22 33]
[ 9 18 27]


In [31]:
a=np.array([10,20,30])
print(np.mean(a))
print(a.mean())

20.0
20.0


In [32]:
a = np.array([10,20,30])
np.average(a,weights=[1,1,0]) # a와 weights 사이에 콤마(,)이다!! 기본값은 [1,1,1]

15.0

In [33]:
a = np.array([10,20,30])
np.median(a)

20.0

In [34]:
x=np.array([10.,20.,30.,15.,10])
y=np.sort(x)
y

array([10., 10., 15., 20., 30.])

In [35]:
a = np.array([10,20,30])
a.min()
a.max()

30

In [36]:
# reshape

a = np.arange(1,7,1)
print(a)

b = a.reshape(2,3)
print(b)

c = np.linspace(1,10,10)
print(c)

d=np.linspace(1,10,10).reshape(2,5)
print(d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [37]:
# repeat

a = np.array([[1,2],[3,4]])
b = np.repeat(a,2)
print(b)

a = np.array([[1,2],[3,4]])
b = np.repeat(a,2,axis=0)
print(b)

a = np.array([[1,2],[3,4]])
b = np.repeat(a,2,axis=1)
print(b)

a = np.array([[1,2],[3,4]])
b = np.repeat(a,[1,2],axis=0) # 세로로 [1,2]를 1번 [3,4]를 2번
print(b)

a = np.array([[1,2],[3,4]])
b = np.repeat(a,[3,1],axis=1) # 가로로 [1,2]를 3번 [3,4]를 1번
print(b)

[1 1 2 2 3 3 4 4]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[[1 1 2 2]
 [3 3 4 4]]
[[1 2]
 [3 4]
 [3 4]]
[[1 1 1 2]
 [3 3 3 4]]


In [38]:
A=np.array([[10,20,30],[40,50,60],[70,80,90]])
B=np.array([[1],[2],[3]])
B=B.repeat(3,axis=1)
A*B

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

# Broadcasting

### Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행

### 연산되는 두 ndarray가 다른 shape을 갖는 경우 브로드캐스팅 후 진행

In [40]:
A=np.array([[10,20,30],[40,50,60],[70,80,90]])
B=np.array([[1],[2],[3]])
C=A*B
C

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])